kind: pipeline
name: integration

steps:
  - name: build
    image: node
    commands:
      - yarn install --frozen-lockfile
      - yarn build
  - name: test
    image: node
    commands:
      - yarn test
    depends_on:
      - build
  - name: lint
    image: node
    commands:
      - yarn lint
    depends_on:
      - build

trigger:
  branch:
    - develop
    - feature/*
    - hotfix/*
    - renovate/*
  event:
    - push