steps:
  build:
    image: node
    commands:
    - yarn install --frozen-lockfile
    - yarn build
    when:
      event: [ push, pull_request ]
      branch: [ hotfix/*, feature/*, renovate/*, develop, main ]
  lint:
    image: node
    commands:
    - yarn lint
    when:
      event: [ push, pull_request ]
      branch: [ hotfix/*, feature/*, renovate/*, develop, main ]
  test:
    image: node
    commands:
    - yarn test
    when:
      event: [ push, pull_request ]
      branch: [ hotfix/*, feature/*, renovate/*, develop, main ]
  publish:
    image: plugins/npm
    settings:
      username:
        from_secret: NPM_USERNAME
      email:
        from_secret: NPM_EMAIL
      password:
        from_secret: NPM_PASSWORD
      api_key:
        from_secret: NPM_TOKEN
    when:
      event: tag
      branch: main